### ISSUE TITLE
Panic on parsing unicode

### ISSUE THREAD

**Issue by cheukyin699** [johannhof/markdown.rs#23]
Minimum Example:

```rust
extern crate markdown;

fn main() {
    let t = markdown::to_html("都");
    println!("{}", t);
}
```

Backtrace:

```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '都' (bytes 0..3) of `都`', /checkout/src/libcore/str/mod.rs:1792
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::str::slice_error_fail
             at /checkout/src/libcore/str/mod.rs:1792
  10: core::str::traits::<impl core::ops::Index<core::ops::Range<usize>> for str>::index
             at /checkout/src/libcore/str/mod.rs:1462
  11: markdown::parser::block::blockquote::parse_blockquote
             at /home/cheukyin699/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/block/blockquote.rs:7
  12: markdown::parser::block::parse_block
             at /home/cheukyin699/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/block/mod.rs:69
  13: markdown::parser::block::parse_blocks
             at /home/cheukyin699/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/block/mod.rs:25
  14: markdown::parser::parse
             at /home/cheukyin699/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/mod.rs:38
  15: markdown::to_html
             at /home/cheukyin699/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/lib.rs:25
  16: testing::main
             at ./src/main.rs:4
  17: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  19: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  20: main
  21: __libc_start_main
  22: _start
```

Suspected line of code at `src/parser/block/blockquote.rs:7. Indexing of string that contains Unicode characters isn't recommended.

**Comment by PENGUINLIONG** [comment]
Maybe [this](https://github.com/johannhof/markdown.rs/pull/22) could help. At least on parsing Chinese it  works properly.

**Comment by cheukyin699** [comment]
@PENGUINLIONG yeah it does; I just wish it would get merged quicker.
